apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-server
  name: go-server-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: go-server
